### ISSUE TITLE
use gopkg.in

### ISSUE THREAD

**Issue by SP1980** [gin-contrib/secure#1]
Hi,

can we change the import from 

    "github.com/gin-gonic/gin"

to

    "gopkg.in/gin-gonic/gin.v1"

to be more compatible with the main project?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
I will move https://github.com/gin-gonic/contrib/blob/master/secure to this place.

**Comment by appleboy** [comment]
@javierprovecho Do you have any concerns about replace source code with https://github.com/gin-gonic/contrib/blob/master/secure ?
