### ISSUE TITLE
Middlware order matters?

### ISSUE THREAD

**Issue by jarmo** [gin-contrib/secure#16]
I've found out that using this middleware had stopped working at some point when I've added some middlewares before this middleware. By moving this middleware to first middleware it resumed working again.

Why would order of using this middleware affect its functionality? Is it because some other middleware might cancel middleware chain? If that's the case then it should definitely be mentioned in the README and/or prevented to be happen somehow by the code itself.

Seems pretty critical from security perspective.

**Comment by bernardo-jac** [comment]
Late but might be useful, Gin creates a handler chain, and handlers run in the same order they're inserted in. This might give you some more context, depending on your handlers.

**Comment by jarmo** [comment]
@bernardo-jac thanks for chiming in :) Yeah, it makes sense reading this totally forgotten issue now. However, I don't see any reason right now for any middleware to disable this, but as I suspect then it is out of control of this middleware per se.

Closing this issue with these thoughts.
